project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*_complete_*.ipynb"
    - "!*.zip"
    - "!*.data"
    - "!datasets/"
    - "!*.names"
    - "!DryBeanDataset/"
    - "!z_recordings/"
  # post-render:
  #   - "cp images/*.svg docs/images/"
  resources:
    - images/*.svg
    - notebooks/python_intermediate_regression_ASRI25.ipynb
    - notebooks/python_intermediate_regression_complete_ASRI25.ipynb

website:
  title: "ASRI-2025"
  navbar: false

format:
  html:
    theme: lux
    grid:
      sidebar-width: 0rem
      body-width: 1200px
      margin-width: 0rem
      gutter-width: 1rem
    css: styles.css